/* tslint:disable */
/* eslint-disable */
/**
 * Twitter Clone API
 * The Twitter Clone API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginatedResponse
 */
export interface PaginatedResponse {
    /**
     * Array of items
     * @type {Array<string>}
     * @memberof PaginatedResponse
     */
    'data': Array<string>;
    /**
     * Number of items to return
     * @type {number}
     * @memberof PaginatedResponse
     */
    'limit': number;
    /**
     * Number of items to skip
     * @type {number}
     * @memberof PaginatedResponse
     */
    'offset': number;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedResponse
     */
    'total': number;
    /**
     * Number of items returned
     * @type {number}
     * @memberof PaginatedResponse
     */
    'count': number;
}

